context:
  version: "4.3"

package:
  name: rarfile
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/r/rarfile/rarfile-${{ version }}.tar.gz
    sha256: 0d8b5a7ffb9f8e9a7b002f2398905e4420c0cb373e799b48e48f418db9c8816a

build:
  script: ${{ PYTHON }} -m pip install .
  noarch: python
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - rarfile
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/markokr/rarfile
  summary: RAR archive reader for Python
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
