context:
  version: 4.2

package:
  name: rarfile
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/r/rarfile/rarfile-${{ version }}.tar.gz
    sha256: 8e1c8e72d0845ad2b32a47ab11a719bc2e41165ec101fd4d3fe9e92aa3f469ef

build:
  script: ${{ PYTHON }} -m pip install .
  noarch: python
  number: 0

requirements:
  host:
    - setuptools
    - python >=3.6
    - pip
  run:
    - python >=3.6

tests:
  - python:
      imports:
        - rarfile
      pip_check: true

extra:
  recipe-maintainers:
    - ShalokShalom

about:
  homepage: https://github.com/markokr/rarfile
  summary: RAR archive reader for Python
  description: |-
    rarfile - RAR archive reader for Python
    =======================================

    This is a Python module for RAR_ archive reading. The interface follows the style of zipfile_. Licensed under ISC_ license....
  license: ISC
  license_file: LICENSE
